# models/schema.yml

version: 2

sources:
  - name: raw     #-> datasete verdiğimiz yeni ad. dataset için schema kullanılır.
    schema: gz_raw_data   #-> datasetin bigquery deki adı
    tables:   #hangi tabloları alacağımızı beliritiriz.
      - name: sales   #->tabloya verdiğimiz yeni ad. tablolar için identifier kullanılır.
        identifier: raw_gz_sales
        description: Greenweez'in satışları / her orders_id'de bulunan bir product_id için bir satırımız var
        # Freshness testing
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: satın alma tarihi
          - name: orders_id
            description: foreign key to ship
          - name: products_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
         - unique:
            column_name: "(orders_id || '-' || pdt_id)"
         - dbt_utils.unique_combination_of_columns:
              arguments:
                 combination_of_columns:
                  - orders_id
                  - pdt_id
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: Primary key
            tests:
            - unique
            - not_null
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:
          - name: orders_id
            description: Primary key
            tests:
            - unique
            - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the distribution centre/warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier/logistics provider
